[project]
name = "ml-from-scratch"
version = "0.1.0"
description = "ml from scratch: number predictor"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.3.1",
    "scikit-learn>=1.7.0",
]
